"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.createTenantFileUploadSession = exports.disconnectGoogleDriveStorage = exports.getGoogleDriveStorageAuthUrl = exports.testWorkspaceFileStorageConnection = exports.saveWorkspaceFileStorageConfig = exports.getWorkspaceFileStorageConfig = exports.fetchWorkspaceFinancialUsage = exports.saveWorkspaceFinancialConfig = exports.getWorkspaceFinancialConfig = exports.deleteWorkspaceApiToken = exports.createWorkspaceApiToken = exports.listWorkspaceApiTokens = exports.saveWorkspaceSmtpConfig = exports.getWorkspaceSmtpConfig = exports.onProjectTaskGitHubSync = exports.facebookCallback = exports.getFacebookAuthUrl = exports.debugHealthSnapshots = exports.dailyHealthSnapshots = exports.autoStartSprints = exports.debugScheduler = exports.checkScheduledPosts = exports.youtubeCallback = exports.getYouTubeAuthUrl = exports.tiktokCallback = exports.getTikTokAuthUrl = exports.submitInitiativeFeedback = exports.getInitiativeFeedbackForm = exports.saveInitiativeFeedbackConfig = exports.callGemini = exports.editImage = exports.generateImage = exports.askCora = exports.sendContactFormEmail = exports.confirmNewsletterSignup = exports.requestNewsletterSignup = exports.confirmWaitlist = exports.requestWaitlist = exports.sendInvitation = exports.sendTestNotification = exports.onNotificationCreated = exports.manageCategories = exports.getCategories = exports.onBlogPostWrite = exports.getBlogPosts = exports.createBlogPost = exports.api = exports.newsletterUnsubscribe = exports.newsletterSubscribe = exports.testSMTPConnection = void 0;
exports.upsertFinanceSettings = exports.upsertFinancePeriod = exports.upsertFinanceAccount = exports.calculateScenarioSnapshot = exports.upsertScenario = exports.migrateLegacyFinanceV1ToV2 = exports.runFinanceSync = exports.upsertFinanceSyncConnection = exports.upsertFinanceAllocationRule = exports.deleteFinanceRecurringTemplate = exports.upsertFinanceRecurringTemplate = exports.buildTaxReport = exports.buildFinancialReports = exports.generateDatevExport = exports.reopenPeriod = exports.runMonthlyClose = exports.confirmReconciliation = exports.suggestReconciliation = exports.importBankStatement = exports.unallocatePayment = exports.allocatePayment = exports.recordPayment = exports.voidBill = exports.postBill = exports.deleteFinanceDocument = exports.linkFinanceDocumentToEntity = exports.deleteFinanceOperationTemplate = exports.upsertFinanceOperationTemplate = exports.recommendFinanceOperations = exports.retryFinanceOperationRun = exports.listFinanceOperationRuns = exports.getFinanceOperationRun = exports.executeFinanceOperation = exports.previewFinanceOperation = exports.versionFinanceDocument = exports.uploadFinanceDocument = exports.extractInvoiceFromDocument = exports.confirmExtractedInvoiceDraft = exports.createBill = exports.advanceInvoiceDunning = exports.voidInvoice = exports.issueInvoice = exports.createInvoice = exports.postJournalEntry = exports.googleDriveStorageCallback = exports.deleteTenantFile = exports.getTenantFileDownloadUrl = exports.getTenantFirebaseStorageDownloadUrl = exports.listTenantFiles = exports.finalizeTenantFileUpload = void 0;
exports.upsertFinanceTaxCode = exports.upsertFinanceVendor = exports.upsertFinanceCustomer = void 0;
require("./init"); // Ensure init runs
const email_1 = require("./email");
Object.defineProperty(exports, "testSMTPConnection", { enumerable: true, get: function () { return email_1.testSMTPConnection; } });
const newsletter_1 = require("./newsletter");
Object.defineProperty(exports, "newsletterSubscribe", { enumerable: true, get: function () { return newsletter_1.newsletterSubscribe; } });
Object.defineProperty(exports, "newsletterUnsubscribe", { enumerable: true, get: function () { return newsletter_1.newsletterUnsubscribe; } });
Object.defineProperty(exports, "api", { enumerable: true, get: function () { return newsletter_1.api; } });
const blog_1 = require("./blog");
Object.defineProperty(exports, "createBlogPost", { enumerable: true, get: function () { return blog_1.createBlogPost; } });
Object.defineProperty(exports, "getBlogPosts", { enumerable: true, get: function () { return blog_1.getBlogPosts; } });
Object.defineProperty(exports, "onBlogPostWrite", { enumerable: true, get: function () { return blog_1.onBlogPostWrite; } });
const categories_1 = require("./categories");
Object.defineProperty(exports, "getCategories", { enumerable: true, get: function () { return categories_1.getCategories; } });
Object.defineProperty(exports, "manageCategories", { enumerable: true, get: function () { return categories_1.manageCategories; } });
const notifications_1 = require("./notifications");
Object.defineProperty(exports, "onNotificationCreated", { enumerable: true, get: function () { return notifications_1.onNotificationCreated; } });
Object.defineProperty(exports, "sendTestNotification", { enumerable: true, get: function () { return notifications_1.sendTestNotification; } });
const invitations_1 = require("./invitations");
Object.defineProperty(exports, "sendInvitation", { enumerable: true, get: function () { return invitations_1.sendInvitation; } });
const waitlist_1 = require("./waitlist");
Object.defineProperty(exports, "requestWaitlist", { enumerable: true, get: function () { return waitlist_1.requestWaitlist; } });
Object.defineProperty(exports, "confirmWaitlist", { enumerable: true, get: function () { return waitlist_1.confirmWaitlist; } });
const newsletter_public_1 = require("./newsletter-public");
Object.defineProperty(exports, "requestNewsletterSignup", { enumerable: true, get: function () { return newsletter_public_1.requestNewsletterSignup; } });
Object.defineProperty(exports, "confirmNewsletterSignup", { enumerable: true, get: function () { return newsletter_public_1.confirmNewsletterSignup; } });
const contact_1 = require("./contact");
Object.defineProperty(exports, "sendContactFormEmail", { enumerable: true, get: function () { return contact_1.sendContactFormEmail; } });
const ai_service_1 = require("./ai-service");
Object.defineProperty(exports, "askCora", { enumerable: true, get: function () { return ai_service_1.askCora; } });
Object.defineProperty(exports, "generateImage", { enumerable: true, get: function () { return ai_service_1.generateImage; } });
Object.defineProperty(exports, "editImage", { enumerable: true, get: function () { return ai_service_1.editImage; } });
Object.defineProperty(exports, "callGemini", { enumerable: true, get: function () { return ai_service_1.callGemini; } });
const initiative_feedback_1 = require("./initiative-feedback");
Object.defineProperty(exports, "getInitiativeFeedbackForm", { enumerable: true, get: function () { return initiative_feedback_1.getInitiativeFeedbackForm; } });
Object.defineProperty(exports, "saveInitiativeFeedbackConfig", { enumerable: true, get: function () { return initiative_feedback_1.saveInitiativeFeedbackConfig; } });
Object.defineProperty(exports, "submitInitiativeFeedback", { enumerable: true, get: function () { return initiative_feedback_1.submitInitiativeFeedback; } });
const tiktok_1 = require("./tiktok");
Object.defineProperty(exports, "getTikTokAuthUrl", { enumerable: true, get: function () { return tiktok_1.getTikTokAuthUrl; } });
Object.defineProperty(exports, "tiktokCallback", { enumerable: true, get: function () { return tiktok_1.tiktokCallback; } });
const youtube_1 = require("./youtube");
Object.defineProperty(exports, "getYouTubeAuthUrl", { enumerable: true, get: function () { return youtube_1.getYouTubeAuthUrl; } });
Object.defineProperty(exports, "youtubeCallback", { enumerable: true, get: function () { return youtube_1.youtubeCallback; } });
const scheduler_1 = require("./scheduler");
Object.defineProperty(exports, "checkScheduledPosts", { enumerable: true, get: function () { return scheduler_1.checkScheduledPosts; } });
Object.defineProperty(exports, "debugScheduler", { enumerable: true, get: function () { return scheduler_1.debugScheduler; } });
Object.defineProperty(exports, "autoStartSprints", { enumerable: true, get: function () { return scheduler_1.autoStartSprints; } });
Object.defineProperty(exports, "dailyHealthSnapshots", { enumerable: true, get: function () { return scheduler_1.dailyHealthSnapshots; } });
Object.defineProperty(exports, "debugHealthSnapshots", { enumerable: true, get: function () { return scheduler_1.debugHealthSnapshots; } });
const facebook_1 = require("./facebook");
Object.defineProperty(exports, "getFacebookAuthUrl", { enumerable: true, get: function () { return facebook_1.getFacebookAuthUrl; } });
Object.defineProperty(exports, "facebookCallback", { enumerable: true, get: function () { return facebook_1.facebookCallback; } });
const github_task_sync_1 = require("./github-task-sync");
Object.defineProperty(exports, "onProjectTaskGitHubSync", { enumerable: true, get: function () { return github_task_sync_1.onProjectTaskGitHubSync; } });
const workspace_admin_1 = require("./workspace-admin");
Object.defineProperty(exports, "createWorkspaceApiToken", { enumerable: true, get: function () { return workspace_admin_1.createWorkspaceApiToken; } });
Object.defineProperty(exports, "deleteWorkspaceApiToken", { enumerable: true, get: function () { return workspace_admin_1.deleteWorkspaceApiToken; } });
Object.defineProperty(exports, "fetchWorkspaceFinancialUsage", { enumerable: true, get: function () { return workspace_admin_1.fetchWorkspaceFinancialUsage; } });
Object.defineProperty(exports, "getWorkspaceFinancialConfig", { enumerable: true, get: function () { return workspace_admin_1.getWorkspaceFinancialConfig; } });
Object.defineProperty(exports, "getWorkspaceSmtpConfig", { enumerable: true, get: function () { return workspace_admin_1.getWorkspaceSmtpConfig; } });
Object.defineProperty(exports, "listWorkspaceApiTokens", { enumerable: true, get: function () { return workspace_admin_1.listWorkspaceApiTokens; } });
Object.defineProperty(exports, "saveWorkspaceFinancialConfig", { enumerable: true, get: function () { return workspace_admin_1.saveWorkspaceFinancialConfig; } });
Object.defineProperty(exports, "saveWorkspaceSmtpConfig", { enumerable: true, get: function () { return workspace_admin_1.saveWorkspaceSmtpConfig; } });
const file_storage_1 = require("./file-storage");
Object.defineProperty(exports, "createTenantFileUploadSession", { enumerable: true, get: function () { return file_storage_1.createTenantFileUploadSession; } });
Object.defineProperty(exports, "deleteTenantFile", { enumerable: true, get: function () { return file_storage_1.deleteTenantFile; } });
Object.defineProperty(exports, "disconnectGoogleDriveStorage", { enumerable: true, get: function () { return file_storage_1.disconnectGoogleDriveStorage; } });
Object.defineProperty(exports, "finalizeTenantFileUpload", { enumerable: true, get: function () { return file_storage_1.finalizeTenantFileUpload; } });
Object.defineProperty(exports, "getGoogleDriveStorageAuthUrl", { enumerable: true, get: function () { return file_storage_1.getGoogleDriveStorageAuthUrl; } });
Object.defineProperty(exports, "getTenantFirebaseStorageDownloadUrl", { enumerable: true, get: function () { return file_storage_1.getTenantFirebaseStorageDownloadUrl; } });
Object.defineProperty(exports, "getTenantFileDownloadUrl", { enumerable: true, get: function () { return file_storage_1.getTenantFileDownloadUrl; } });
Object.defineProperty(exports, "getWorkspaceFileStorageConfig", { enumerable: true, get: function () { return file_storage_1.getWorkspaceFileStorageConfig; } });
Object.defineProperty(exports, "googleDriveStorageCallback", { enumerable: true, get: function () { return file_storage_1.googleDriveStorageCallback; } });
Object.defineProperty(exports, "listTenantFiles", { enumerable: true, get: function () { return file_storage_1.listTenantFiles; } });
Object.defineProperty(exports, "saveWorkspaceFileStorageConfig", { enumerable: true, get: function () { return file_storage_1.saveWorkspaceFileStorageConfig; } });
Object.defineProperty(exports, "testWorkspaceFileStorageConnection", { enumerable: true, get: function () { return file_storage_1.testWorkspaceFileStorageConnection; } });
const finance_v2_1 = require("./finance-v2");
Object.defineProperty(exports, "allocatePayment", { enumerable: true, get: function () { return finance_v2_1.allocatePayment; } });
Object.defineProperty(exports, "buildFinancialReports", { enumerable: true, get: function () { return finance_v2_1.buildFinancialReports; } });
Object.defineProperty(exports, "buildTaxReport", { enumerable: true, get: function () { return finance_v2_1.buildTaxReport; } });
Object.defineProperty(exports, "calculateScenarioSnapshot", { enumerable: true, get: function () { return finance_v2_1.calculateScenarioSnapshot; } });
Object.defineProperty(exports, "confirmReconciliation", { enumerable: true, get: function () { return finance_v2_1.confirmReconciliation; } });
Object.defineProperty(exports, "confirmExtractedInvoiceDraft", { enumerable: true, get: function () { return finance_v2_1.confirmExtractedInvoiceDraft; } });
Object.defineProperty(exports, "createBill", { enumerable: true, get: function () { return finance_v2_1.createBill; } });
Object.defineProperty(exports, "createInvoice", { enumerable: true, get: function () { return finance_v2_1.createInvoice; } });
Object.defineProperty(exports, "deleteFinanceDocument", { enumerable: true, get: function () { return finance_v2_1.deleteFinanceDocument; } });
Object.defineProperty(exports, "deleteFinanceRecurringTemplate", { enumerable: true, get: function () { return finance_v2_1.deleteFinanceRecurringTemplate; } });
Object.defineProperty(exports, "advanceInvoiceDunning", { enumerable: true, get: function () { return finance_v2_1.advanceInvoiceDunning; } });
Object.defineProperty(exports, "extractInvoiceFromDocument", { enumerable: true, get: function () { return finance_v2_1.extractInvoiceFromDocument; } });
Object.defineProperty(exports, "generateDatevExport", { enumerable: true, get: function () { return finance_v2_1.generateDatevExport; } });
Object.defineProperty(exports, "importBankStatement", { enumerable: true, get: function () { return finance_v2_1.importBankStatement; } });
Object.defineProperty(exports, "issueInvoice", { enumerable: true, get: function () { return finance_v2_1.issueInvoice; } });
Object.defineProperty(exports, "migrateLegacyFinanceV1ToV2", { enumerable: true, get: function () { return finance_v2_1.migrateLegacyFinanceV1ToV2; } });
Object.defineProperty(exports, "postBill", { enumerable: true, get: function () { return finance_v2_1.postBill; } });
Object.defineProperty(exports, "postJournalEntry", { enumerable: true, get: function () { return finance_v2_1.postJournalEntry; } });
Object.defineProperty(exports, "recordPayment", { enumerable: true, get: function () { return finance_v2_1.recordPayment; } });
Object.defineProperty(exports, "reopenPeriod", { enumerable: true, get: function () { return finance_v2_1.reopenPeriod; } });
Object.defineProperty(exports, "runMonthlyClose", { enumerable: true, get: function () { return finance_v2_1.runMonthlyClose; } });
Object.defineProperty(exports, "runFinanceSync", { enumerable: true, get: function () { return finance_v2_1.runFinanceSync; } });
Object.defineProperty(exports, "suggestReconciliation", { enumerable: true, get: function () { return finance_v2_1.suggestReconciliation; } });
Object.defineProperty(exports, "unallocatePayment", { enumerable: true, get: function () { return finance_v2_1.unallocatePayment; } });
Object.defineProperty(exports, "linkFinanceDocumentToEntity", { enumerable: true, get: function () { return finance_v2_1.linkFinanceDocumentToEntity; } });
Object.defineProperty(exports, "listFinanceOperationRuns", { enumerable: true, get: function () { return finance_v2_1.listFinanceOperationRuns; } });
Object.defineProperty(exports, "upsertFinanceAllocationRule", { enumerable: true, get: function () { return finance_v2_1.upsertFinanceAllocationRule; } });
Object.defineProperty(exports, "upsertFinanceOperationTemplate", { enumerable: true, get: function () { return finance_v2_1.upsertFinanceOperationTemplate; } });
Object.defineProperty(exports, "upsertFinanceAccount", { enumerable: true, get: function () { return finance_v2_1.upsertFinanceAccount; } });
Object.defineProperty(exports, "upsertFinanceCustomer", { enumerable: true, get: function () { return finance_v2_1.upsertFinanceCustomer; } });
Object.defineProperty(exports, "upsertFinancePeriod", { enumerable: true, get: function () { return finance_v2_1.upsertFinancePeriod; } });
Object.defineProperty(exports, "upsertFinanceRecurringTemplate", { enumerable: true, get: function () { return finance_v2_1.upsertFinanceRecurringTemplate; } });
Object.defineProperty(exports, "upsertFinanceSettings", { enumerable: true, get: function () { return finance_v2_1.upsertFinanceSettings; } });
Object.defineProperty(exports, "upsertFinanceSyncConnection", { enumerable: true, get: function () { return finance_v2_1.upsertFinanceSyncConnection; } });
Object.defineProperty(exports, "upsertFinanceTaxCode", { enumerable: true, get: function () { return finance_v2_1.upsertFinanceTaxCode; } });
Object.defineProperty(exports, "upsertFinanceVendor", { enumerable: true, get: function () { return finance_v2_1.upsertFinanceVendor; } });
Object.defineProperty(exports, "uploadFinanceDocument", { enumerable: true, get: function () { return finance_v2_1.uploadFinanceDocument; } });
Object.defineProperty(exports, "versionFinanceDocument", { enumerable: true, get: function () { return finance_v2_1.versionFinanceDocument; } });
Object.defineProperty(exports, "previewFinanceOperation", { enumerable: true, get: function () { return finance_v2_1.previewFinanceOperation; } });
Object.defineProperty(exports, "executeFinanceOperation", { enumerable: true, get: function () { return finance_v2_1.executeFinanceOperation; } });
Object.defineProperty(exports, "getFinanceOperationRun", { enumerable: true, get: function () { return finance_v2_1.getFinanceOperationRun; } });
Object.defineProperty(exports, "retryFinanceOperationRun", { enumerable: true, get: function () { return finance_v2_1.retryFinanceOperationRun; } });
Object.defineProperty(exports, "recommendFinanceOperations", { enumerable: true, get: function () { return finance_v2_1.recommendFinanceOperations; } });
Object.defineProperty(exports, "deleteFinanceOperationTemplate", { enumerable: true, get: function () { return finance_v2_1.deleteFinanceOperationTemplate; } });
Object.defineProperty(exports, "upsertScenario", { enumerable: true, get: function () { return finance_v2_1.upsertScenario; } });
Object.defineProperty(exports, "voidBill", { enumerable: true, get: function () { return finance_v2_1.voidBill; } });
Object.defineProperty(exports, "voidInvoice", { enumerable: true, get: function () { return finance_v2_1.voidInvoice; } });
__exportStar(require("./passkeys"), exports);
//# sourceMappingURL=index.js.map